[project]
name = "jarvis-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "ddgs>=9.14.4",
    "fastapi>=0.139.0",
    "httpx>=0.28.1",
    "keyring>=25.7.0",
    "nvidia-ml-py>=13.610.43",
    "playwright>=1.61.0",
    "psutil>=7.2.2",
    "python-dotenv>=1.2.2",
    "sqlite-vec>=0.1.9",
    "uvicorn[standard]>=0.51.0",
]
